require 'configs.lualine'
require 'configs.colors'
-- require 'configs.catppuccin'
require 'configs.cloak'
require 'configs.zenmode'
require 'configs.nvim-comment'
require 'configs.undotree'
require 'configs.treesitter'
require 'configs.trouble'
require 'configs.nvim-tree'
require 'configs.todo-comments'
require 'configs.telescope'
require 'configs.fugitive'
require 'configs.lsp'
require 'configs.harpoon'
require 'configs.cmp'
require 'configs.luasnip'

require 'configs.tmux-navigate'
require 'configs.cord'
require 'configs.refactoring'
require 'configs.mini'
require 'configs.hacker'
require 'configs.randiverse'
require 'configs.nvim-ts-autotag'
require 'configs.gitsigns'
require 'configs.conform'
require 'configs.ibl'
require 'configs.which-key'

require 'configs.dap'
require 'configs.clang-extensions'
-- require 'configs.outline'
-- require 'configs.lsp-lens'
require 'configs.peek'
require 'configs.package-info'
require 'configs.supermaven'
-- require 'configs.toggleterm'
require 'configs.nvim-ufo'
require 'configs.duck-commit'
-- require 'configs.silicon'
-- require 'configs.dbee'
require 'configs.transparent'
-- require('configs.airline')
-- require('configs.autopairs')
-- require('configs.autotag')
-- require 'configs.obsidian'
