hard_tabs = false
tab_spaces = 2
max_width = 120
reorder_imports = true
match_block_trailing_comma = true
match_arm_leading_pipes = "Preserve"
edition = "2024"

# Keep things on one line as much as possible
use_small_heuristics = "Max"
