
# .stylua.toml
# Configuration file for the StyLua Lua code formatter.

# Line ending style: "Unix" (LF) or "Windows" (CRLF)
line_endings = "Unix"

# Indentation settings
indent_type = "Spaces"   # or "Tabs"
indent_width = 2
column_width = 100       # Max line length

# Quote style
quote_style = "AutoPreferSingle"  # or AutoPreferDouble, AlwaysSingle, AlwaysDouble

# Function call parentheses
call_parentheses = "None"  # or Always, PreferNone, PreferAlways

# Automatically sort `require` statements
[sort_requires]
enabled = true
