require('configs.lualine')
require('configs.cloak')
require('configs.harpoon')
require('configs.colors')
require('configs.zenmode')
require('configs.comment')
require('configs.undotree')
require('configs.treesitter')
require('configs.trouble')
require('configs.nvim-tree')
require('configs.todo-comments')
require('configs.telescope')
require('configs.fugitive')

--require('configs.refactoring')
-- require('configs.iblconf')
require('configs.lsp')
-- require('configs.null-ls')
-- require('configs.autopairs')
-- require('configs.autotag')
-- require('configs.tmux-navigate')
-- require('configs.cmp')
-- require('configs.mini')
-- require('configs.wich-key')
