require 'configs.lualine'
-- require 'configs.catppuccin'
require 'configs.cloak'
require 'configs.harpoon'
require 'configs.colors'
require 'configs.zenmode'
require 'configs.comment'
require 'configs.undotree'
require 'configs.treesitter'
require 'configs.trouble'
require 'configs.nvim-tree'
require 'configs.todo-comments'
require 'configs.telescope'
require 'configs.fugitive'
require 'configs.lsp'
require 'configs.null-ls'
require 'configs.cmp'
require 'configs.luasnip'

require 'configs.tmux-navigate'
require 'configs.presence'
require 'configs.refactoring'
require 'configs.mini'
require 'configs.hacker'
require 'configs.randiverse'
require 'configs.nvim-ts-autotag'
require 'configs.silicon'
-- require 'configs.transparent'
require 'configs.gitsigns'
require 'configs.conform'
require 'configs.ibl'
require 'configs.which-key'

-- require('configs.airline')
-- require('configs.autopairs')
-- require('configs.autotag')
require 'configs.dap'
-- require 'configs.obsidian'
require 'configs.dbee'
