# HyprFlux — https://github.com/ahmad9059/HyprFlux
# Hypridle

general {
    lock_cmd = pidof hyprlock || hyprlock # runs hyprlock if it is not already running (this is always run when "loginctl lock-session" is called)
    # unlock_cmd = killall hyprlock # kills hyprlock when unlocking (this is always run when "loginctl unlock-session" is called)
    before_sleep_cmd = loginctl lock-session    # ensures that the session is locked before going to sleep
    after_sleep_cmd = hyprctl dispatch dpms on # turn of screen after sleep (not strictly necessary, but just in case)
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
}

# Warn
listener {
    timeout = 540                     # 9 min
    on-timeout = notify-send "You are idle!"
    on-resume = notify-send "Oh! you're Back" "Hello !!!"
}

# Screenlock
listener {
    timeout = 600                     # 10 min
    on-timeout = loginctl lock-session
}
