# ============================================================================
# Hyprpaper — Wallpaper
# ============================================================================

preload = /home/wildduck/.config/hypr/bgs/bg.jpg
wallpaper = , /home/wildduck/.config/hypr/bgs/bg.jpg

splash = false
ipc = off
