# Decoration Settings — i3-style with active border

# HyprFlux static color palette
source = $HOME/.config/hypr/hyprflux-colors/hyprflux-colors.conf

general {
  border_size = 2
  gaps_in = 2
  gaps_out = 2

  col.active_border = $color12
  col.inactive_border = $color0
}

decoration {
  rounding = 0

  active_opacity = 1.0
  inactive_opacity = 1.0
  fullscreen_opacity = 1.0

  dim_inactive = false

  shadow {
    enabled = false
  }

  blur {
    enabled = false
  }
}

group {
  col.border_active = $color15

  groupbar {
    col.active = $color0
  }
}
