# i3blocks configuration file
# https://vivien.github.io/i3blocks

# Global properties
separator=true
separator_block_width=15

[spotify]
label=
command=/home/$USER/.config/scripts/spotify.py
color=#81b71a
interval=5

[volume]
command=/home/$USER/.config/scripts/volume
LABEL=♪
interval=1
signal=10
MIXER=default

[disk]
command=/home/$USER/.config/scripts/disk
LABEL=
interval=30

[memory]
command=/home/$USER/.config/scripts/memory
label=
interval=30

[time]
command=date '+%Y-%m-%d %H:%M:%S'
interval=1

[arch-update]
command=/home/$USER/.config/scripts/arch-update
interval=3600
markup=pango
LABEL=
