general {
    colors = true
    color_good = "#a6e3a1"
    color_degraded = "#f9e2af"
    color_bad = "#f38ba8"
    interval = 5
    output_format = "i3bar"
}

order += "wireless _first_"
order += "ethernet _first_"
order += "battery all"
order += "disk /"
order += "memory"
order += "cpu_usage"
order += "volume master"
order += "tztime local"

wireless _first_ {
    format_up = "W: %essid %quality"
    format_down = "W: down"
}

ethernet _first_ {
    format_up = "E: %ip"
    format_down = ""
}

battery all {
    format = "BAT: %status %percentage %remaining"
    format_down = ""
    low_threshold = 20
    threshold_type = "percentage"
}

disk "/" {
    format = "DISK: %avail"
}

memory {
    format = "MEM: %used / %total"
    threshold_degraded = "1G"
    threshold_critical = "200M"
}

cpu_usage {
    format = "CPU: %usage"
}

volume master {
    format = "VOL: %volume"
    format_muted = "VOL: muted"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

tztime local {
    format = "%Y-%m-%d %H:%M:%S"
}
